cabal-version:      3.0
name:               calculator
version:            0.1.0.0
author:             holmen1
category:           Testing
build-type:         Simple

executable calculator
    main-is:          Calculator.hs
    build-depends:    base ^>=4.17.2.1,
                      HUnit
    default-language: Haskell2010
                      
