module Calculator where

import Data.List
import Test.HUnit

{- Reverse Polish notation calculator -}
-- 10 4 3 + 2 * - = 10 - (4 + 3) * 2 = -4
-- RPN "10 4 3 + 2 * -" = -4

type Expression = String
type ExpressionList = [Expression]
type CalcStack = [Float]

stringToExpressionList :: String -> ExpressionList
stringToExpressionList = words

foldingFunction :: CalcStack -> Expression -> CalcStack
foldingFunction (x:y:ys) "*" = (x * y):ys
foldingFunction (x:y:ys) "+" = (x + y):ys
foldingFunction (x:y:ys) "-" = (y - x):ys
foldingFunction xs numberString = read numberString:xs

{- The foldl function is a left fold that processes the list of expressions generated by
stringToExpressionList. It uses foldingFunction to iteratively apply each expression to
a stack (initially an empty list []). The foldingFunction handles the logic for applying
operators to the top elements of the stack or pushing numbers onto the stack. The result
of this fold is a stack with the final result of the RPN expression at the top. -}
solveRPN :: String -> Float
solveRPN = head . foldl foldingFunction [] . stringToExpressionList

{- UI -}
main :: IO ()
main = do
    putStrLn "RPN Calculator"
    calculatorLoop

calculatorLoop :: IO ()
calculatorLoop = do
    putStr "RPN>> "
    expression <- getLine
    if null expression
        then return ()
        else do
            let result = solveRPN expression
            putStrLn $ show result
            calculatorLoop

{- Unit Tests -}                      
wordTest = TestCase (assertEqual "words" ["10","4","3","+","2","*","-"]
                                         (stringToExpressionList "10 4 3 + 2 * -" ))
readTest = TestCase (assertEqual "read" 4
                                        (read "4"))
rpnTest = TestCase (assertEqual "rpn" (-4.0)
                                      (solveRPN "10 4 3 + 2 * -"))

tests = TestList [wordTest,
                  readTest,
                  rpnTest]


